from PIL import Image
import os

public_images_dir = r"c:\Users\ACER\Desktop\Dr Varun Dental Website\public\images"

def resize_image(file_name, new_size, output_name=None, quality=80):
    src_path = os.path.join(public_images_dir, file_name)
    dest_path = os.path.join(public_images_dir, output_name if output_name else file_name)
    
    if not os.path.exists(src_path):
        print(f"File not found: {src_path}")
        return
        
    try:
        with Image.open(src_path) as img:
            w, h = img.size
            print(f"Opening {file_name}: current size {w}x{h}")
            img_resized = img.resize(new_size, Image.Resampling.LANCZOS)
            img_resized.save(dest_path, "WEBP", quality=quality)
            print(f"Saved {dest_path} with size {new_size}")
    except Exception as e:
        print(f"Error resizing {file_name}: {e}")

# 1. Resize Logo to 180x153
print("Resizing Logo...")
resize_image("dr-varun-dental-clinic-logo.webp", (180, 153), quality=85)
# Also overwrite the mobile one generated by the previous script
resize_image("dr-varun-dental-clinic-logo.webp", (180, 153), "dr-varun-dental-clinic-logo-mobile.webp", quality=85)

# 2. Resize Confident Smile Image to 600x600 (Desktop) and 360x360 (Mobile)
print("Resizing Confident Smile Image...")
resize_image("confident-smile-dental-care-viman-nagar.webp", (600, 600), quality=80)
resize_image("confident-smile-dental-care-viman-nagar.webp", (360, 360), "confident-smile-dental-care-viman-nagar-mobile.webp", quality=80)

# 3. Resize Hero Image Desktop to 600x900 (instead of 800x1200)
print("Resizing Hero Image Desktop...")
resize_image("home-dental-clinic-hero-viman-nagar.webp", (600, 900), quality=80)

print("Custom Resizing Complete.")
